site_name: Vellum
site_description: The Precision ODM for Asynchronous MongoDB & Pydantic
site_url: https://wailbentafat.github.io/Vellum
repo_url: https://github.com/wailbentafat/Vellum
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Installation: installation.md
  - Models: models.md
  - Queries: queries.md
  - Repository: repository.md
  - Aggregation: aggregation.md
  - Updates: updates.md
  - Advanced: advanced.md
  - Blog:
    - "Part 1: Typing MongoDB at the Speed of Thought": blog/part-1-typing-mongodb.md
    - "Part 2: Architecture Decisions That Almost Broke Us": blog/part-2-architecture.md
    - "Part 3: What We Won, What We Lost": blog/part-3-tradeoffs.md
