[project]
name = "vellum-odm"
version = "0.1.1"
description = "The Precision ODM for Asynchronous MongoDB & Pydantic."
authors = [
    {name = "bentafat wail", email = "150479778+wailbentafat@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
keywords = ["mongodb", "odm", "pydantic", "async", "motor", "database"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Typing :: Typed",
]
dependencies = [
    "pydantic>=2.0",
    "motor>=3.2,<4.0",
    "pymongo>=4.0,<5.0",
    "cryptography>=44.0",
]

[project.urls]
Homepage = "https://github.com/wailbentafat/vellum"
Repository = "https://github.com/wailbentafat/vellum"
Documentation = "https://github.com/wailbentafat/vellum"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vellum"]

[tool.hatch.build.targets.sdist]
include = ["src/vellum"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "UP"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

